#!/usr/bin/python
# -*- coding: utf-8 -*-
#coding=utf-8
import smtplib
from email.mime.text import MIMEText
msg_from='1942458629@qq.com'
passwd='nyhciqnpctgwdjgi'
msg_to='57820048@qq.com'

subject="2019144112张光娜"
content="开启校园网：手机ip为10.101.92.13  网址查询为30.129.40.48   开启数据：手机ip为10.59.25.207   网址查询为108.162.215.120"
msg=MIMEText(content)
msg['Subject']=subject
msg['From']=msg_from
msg['To']=msg_to
try:
    s=smtplib.SMTP_SSL("smtp.qq.com",465)
    s.login(msg_from,passwd)
    s.sendmail(msg_from,msg_to,msg.as_string())
    print("发送成功")
except(s.SMTPException,e):
    print("发送失败")
finally:
    s.quit()
